POST http://localhost:5000/seller/product/add
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWxsZXIiOiI2MjM5OGUwMDE1ZmNlY2EyODA0Nzk5YzUiLCJpYXQiOjE2NDc5MzkwNzIsImV4cCI6MTY0ODE5ODI3Mn0.BjpCKhtsRswkFjMuaH0JT19MsygU4F03Bc_rEeuQBVo
Content-Type: application/json

{
  "title": "Product 1",
  "description" : {
    "main": "hello hhhhhhhhhhhhh hhhhhhhhhhhhh hhhhhhhhhh hhhhhhhhhh jjjjjjj jjjjjjj jjjj jjjjjj jjjj j jj jjjjjjjj juuuuuuu uu u",
    "feeding_guide": {
      "small" : "2 spoons",
      "medium" : "3 spoons",
      "large" : "4 spoons"
    }
  },
  "allowed": 2,
  "stock": 1000,
  "sizes": [{
    "price": 1099,
    "retail_price": 1199,
    "size": "small"
  },{
    "price": 1699,
    "retail_price": 1999,
    "size": "normal"
  },{
    "price": 2099,
    "retail_price": 2199,
    "size": "large"
  }],
  "seller": "61e2f58aaff1c523fc1da3f2",
  "uci": "100",
  "dddd":"ffff"
}

###

PATCH http://localhost:5000/user/cart/add
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjFlMmY0NGQyODMxNzkxYjE4NTIxMDUzIiwiaWF0IjoxNjQ0MzA3OTA4LCJleHAiOjE2NDQ1NjcxMDh9.vyXX_FNjgLESoDgyrAR-uGrqZnE_eXt_K7erzNgDrDc

{
  "cart":{
    "_id":"620233d5adb0ed0cf0e2c277"
  }
}

###

PATCH http://localhost:5000/user/cart/remove
Content-Type: application/json
{
  "cart":{
    "_id":"620233d5adb0ed0cf0e2c277"
  }
}

###
POST http://localhost:5000/seller/register
Content-Type: application/json

{
  "email": "sssss@gmail.com",
  "pass": "Nishant"
}